name: Bug Report
description: Problems with vgraph_nav
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a vgraph_nav Bug Report!

  - type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) I encourage you to submit a [Pull Request](https://github.com/Alpaca-zip/vgraph_nav/pulls) (PR) to help improve vgraph_nav for everyone, especially if you have a good understanding of how to implement a fix or feature.
      options:
        - label: Yes I'd like to help by submitting a PR!
