name: ROS1 Industrial CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  black_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run industrial_ci
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: noetic # Replace noetic for your chosen distro.
          BLACK_CHECK: true

  catkin_lint_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run industrial_ci
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: noetic # Replace noetic for your chosen distro.
          BEFORE_BUILD_TARGET_WORKSPACE: 'apt update -q && python3 -m pip install -q -r requirements.txt'
          UPSTREAM_WORKSPACE: .rosinstall
          CATKIN_LINT: true

  build_check:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        env:
          - ROS_DISTRO: noetic # Replace noetic for your chosen distro.
            ROS_REPO: main
            UPSTREAM_WORKSPACE: .rosinstall
            BEFORE_BUILD_TARGET_WORKSPACE: 'apt update -q && python3 -m pip install -q -r requirements.txt'
            IMMEDIATE_TEST_OUTPUT: true
          - ROS_DISTRO: noetic # Replace noetic for your chosen distro.
            ROS_REPO: testing
            UPSTREAM_WORKSPACE: .rosinstall
            BEFORE_BUILD_TARGET_WORKSPACE: 'apt update -q && python3 -m pip install -q -r requirements.txt'
            IMMEDIATE_TEST_OUTPUT: true

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run industrial_ci
        uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
